### ISSUE TITLE
Question: converting MAME source files to CHD for Mario Kart Arcade

### ISSUE THREAD

**Issue by tjanas** [FIX94/triforce-iso-extract#2]
In MAME, I see the CHD for F-Zero AX, but do not see CHDs for Mario Kart Arcade GP and GP2. What is the process for converting the MAME files for Mario Arcade GP?

**Comment by Zopolis4** [comment]
There are not mame CHD's for the Mario Kart Arcade GP games, as there are no good dumps of GP 1 or 2. You can use [this ](https://github.com/FIX94/triforce-nand-iso-extract)to extract a usable image by combining dumps together.
